### ISSUE TITLE
Update links to CCPForge in wiki

### ISSUE THREAD

**Issue by dpo** [ralna/CUTEst#19]

**Comment by nimgould** [comment]
I don't think there are any CCP forge links on the wiki. Everything now points to the github page (which I hope people will use). There are also alternative links to ftp.cuter, but these only work with older browsers (new ones have disabled ftp access for unnamed security reasons, i.e., they couldn't be bothered to maintain them!).

**Comment by dpo** [comment]
I got thrown off by the `svn` commands. Do those work? If so, this issue can be closed.

**Comment by nimgould** [comment]
I still use svn by preference when I can (and gitlab supports both using cleverness under the hood).
So, yes, they still work; we point to the git alternatives for the youngsters

**Comment by agreppin** [comment]
This link has a typo in the wiki: http://github.com/ralna/ARCHDdefs (should be ARCHDefs).

**Comment by nimgould** [comment]
Thank you. Corrected

**Comment by agreppin** [comment]
There is a second one in the git line that has the same problem:
git clone https://github.com/ralna/ARCHDefs ./archdefs
