### ISSUE TITLE
Error in gen77.F

### ISSUE THREAD

**Issue by amontoison** [ralna/CUTEst#47]
```shell
../src/gen77/gen77.F:5:1:

    5 | C     ( Last modified on 23 Dec 2000 at 22:01:38 )
      | 1
Error: Unclassifiable statement at (1)
../src/gen77/gen77.F:77:59:

   77 |          IF( BL( I ) .GT. -INFTY .OR. BU( I ) .LT. INFTY )
      |                                                           1
Error: Syntax error in IF-clause after (1)
../src/gen77/gen77.F:78:7:

   78 |      *       NBNDS = NBNDS + 1
      |       1
Error: Invalid character in name at (1)
```
We have three folders `gen77`, `gen90` and `genc`.
What should we compile with the Meson build system.

**Comment by nimgould** [comment]
These are examples for fortran 77, fortran 90 and C users. The issue above would suggest that the compiler thinks that this is fortran 90 (new source form) when it is deliberatly fortran 77 (old source form).

**Comment by amontoison** [comment]
Thanks Nick!
I did a mistake during the preprocessing (gen77.F -> gen77.f90).
I fixed it.
