### ISSUE TITLE
Wrong headers in cutest.h

### ISSUE THREAD

**Issue by amontoison** [ralna/CUTEst#58]
I am working on a revamp of `CUTEst.jl` and I wanted to generate all Julia wrappers with Clang.jl like I did for GALAHAD but two wrappers were missing.
I implemented the wrappers myself but we should add it in `cutest.h` here:
```julia
function cutest_uofg_(status, n, x, f, g, grad)
  @ccall cutest_lib_path.cutest_uofg_(status::Ptr{Cint}, n::Ptr{Cint}, x::Ptr{Float64},
                                      f::Ptr{Float64}, g::Ptr{Float64}, grad::Ptr{Bool})::Cvoid
end

function cutest_uofg_s_(status, n, x, f, g, grad)
  @ccall cutest_lib_path.cutest_uofg_(status::Ptr{Cint}, n::Ptr{Cint}, x::Ptr{Float32},
                                      f::Ptr{Float32}, g::Ptr{Float32}, grad::Ptr{Bool})::Cvoid
end

function cutest_uhprod_(status, n, goth, x, vector, result)
  @ccall cutest_lib_path.cutest_uhprod_(status::Ptr{Cint}, n::Ptr{Cint}, goth::Ptr{Cint},
                                        x::Ptr{Float64}, vector::Ptr{Float64},
                                        result::Ptr{Float64})::Cvoid
end

function cutest_uhprod_s(status, n, goth, x, vector, result)
  @ccall cutest_lib_path.cutest_uhprod_(status::Ptr{Cint}, n::Ptr{Cint}, goth::Ptr{Float32},
                                        x::Ptr{Float32}, vector::Ptr{Float32},
                                        result::Ptr{Float32})::Cvoid
end
```
Reference: https://github.com/JuliaSmoothOptimizers/CUTEst.jl/pull/333

**Comment by nimgould** [comment]
I am not sure I understand. cutest.h already contains those function shortcuts

**Comment by amontoison** [comment]
It seems that you add some `cint_` in the name of the routines with macros. Is it what you want or an error with a `sed` command?
The name of Julia wrappers generated from `cutest.h` is `cutest_cint_uofg_`.

**Comment by nimgould** [comment]
Wow, it has been like this since the beginning of cutest. I wonder why? As you say, it might simply have been a transaltion blunder. @jfowkes what names do you use for python for these routines?

**Comment by jfowkes** [comment]
I've been happily using `CUTEST_uofg` and `CUTEST_uhprod` from `cutest.h` these exist and both macOS and Linux compilers are happy with these (I tested them only yesterday when I did a new PyCUTEst bugfix release):
https://github.com/jfowkes/pycutest/blob/master/pycutest/c_interface.py#L664
https://github.com/jfowkes/pycutest/blob/master/pycutest/c_interface.py#L1309

**Comment by jfowkes** [comment]
I rather suspect the mapping of CUTEST_uofg to CUTEST_cint_uofg_ is necessary as that is what gfortran calls them... With CUTEst we are going from C straight into F77 with a direct call, but the Fortran compilers make up their own C names...

**Comment by jfowkes** [comment]
@nimgould @amontoison the Fortran routine itself is called `CUTEST_Cint_uofg` so there is no reason why it should not be found in your shared library (unless you're not compiling everything?):
https://github.com/ralna/CUTEst/blob/master/src/tools/uofg.F90#L14

**Comment by nimgould** [comment]
Oh yes, now I remember, it is beacuse the fortran side has logicals, and these may be different from c_bools. The _cint_ routine simply maps logicals to c_bools. cutest.h is picking up the relevant C interface, so it should work for julia and python

**Comment by amontoison** [comment]
Thanks for the clarification, Nick and Jari!
Both symbols `cutest_uofg_` and `cutest_cint_uofg_` are available in the shared library, but the old Julia interface is using `cutest_uofg_` (not a good idea).
I will switch to `cutest_cint_uofg_`.
I close the issue.

**Comment by jfowkes** [comment]
@amontoison note that there are a few other CUTEst routines that also use the `cutest_cint_*` variants in the C interface for the reasons Nick has mentioned (see `cutest.h` for details).

**Comment by amontoison** [comment]
@jfowkes I found four errors in `cutest.h`.
The following routines don't exist in the library:
- `cutest_cint_csgrp`
- `cutest_cint_csjp`
- `cutest_cint_csgrshp`
- `cutest_cint_cchprodsp`

None of these routines have a `Bool` argument, so the macro defining the symbol is incorrect. It should generate:
- `cutest_csgrp`
- `cutest_csjp`
- `cutest_csgrshp`
- `cutest_cchprodsp`

As a workaround, I patched my generator for Julia wrappers: 
https://github.com/JuliaSmoothOptimizers/CUTEst.jl/pull/344/files#diff-cf08fd6ce776128c6927eff66bf852d073b472a41d7e480bf938cfb1c097e8c6R35-R39

**Comment by nimgould** [comment]
Well spotted. cutest.h updated
