### ISSUE TITLE
How to determine the number of nnzj for linear and non-linear constraints in the Jacobian?

### ISSUE THREAD

**Issue by amontoison** [ralna/CUTEst#59]
Is it possible to determine the number of `nnzj` related to linear constraints and non-linear constraints in the Jacobian?
The function `cdimsj` only provides the sum of `lin_nnzj` and `nln_nnzj`.

**Comment by nimgould** [comment]
I'll think about it, it should be possible

**Comment by nimgould** [comment]
Yes, it is straightforward. I presume you mean general linear (as opposed to simple bounds),
and that a two-sided constraint c^L_i <= a_i^T x <= c_^U_i counts as one (not two) constraint(s).
In that case, we simply 
 m_l = 0
 DO i = 1, data%ng
  if ( data%KNDOFC( i ) > 0 .AND.  data%GXEQX( i ) .AND. data%ISTADG( i ) >= data%ISTADG( i + 1 ) & 
  m_l = m_l + 1
END DO
This can easily be made into a tool, but that is a day's work (documentation, tests, etc). Alternatively, do a man on cutest_csetup, and look for how many components of the  logical array LINEAR are true

**Comment by amontoison** [comment]
@nimgould Do you count the number of linear constraints or the number of non-zeros in the Jacobian related to linear constraints `sum( nnz(a_i) )`?

**Comment by nimgould** [comment]
That depends what the question is, if you want to know how many linear constraints there are, it is the former. I'm not sure anyone has ever asked for the latter

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nimgould** [comment]
It would be simple to compute the other by finding the row number for each nonzero in the Jacobian, and counting those for which the linear logical is true

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by amontoison** [comment]
Thanks @nimgould!
I followed your suggestion in [CUTEst.jl](https://github.com/JuliaSmoothOptimizers/CUTEst.jl/pull/351/commits/c95cf271a86d1180159ebbbbf6513b1a80e6149b#diff-4439b24aa0d88d7b848e34d6318dcba50ea599b7ef9ab37f879d68cbd6c7023bR179-R186).
