### ISSUE TITLE
[Feature] Add a routine cutest_ccf_r_

### ISSUE THREAD

**Issue by amontoison** [ralna/CUTEst#65]
Right now, we don't have a routine dedicated solely to evaluating the constraints function, but we do have some alternatives:
- `cutest_cfn` (objective + constraints)
- `cutest_cifn` (individual constraint)
- `cutest_ccfsg` (constraints + Jacobian)

`cutest_ccfsg` seems to be the best option because we can set `grad = false` and `lj = 0`.

A new routine `ccf` with the minimum number of arguments could be a nice new feature, but it requires some work...  
Let's see if someone else needs it in the future and revisit the priority.

cf: https://github.com/ralna/CUTEst/issues/63#issuecomment-2310433077

**Comment by nimgould** [comment]
Hold off the release of CUTEst.jl for one more day. As ... today is a privalege day at RAL, no work, another holiday etc. So for one day only, as I have time, you will get a brand new cutest_ccf, with tests, interfaces and documentation, all for the incredible price of $0, that's right $0.

More later when I've walked the walk

**Comment by nimgould** [comment]
Your wish is my command. New ccf tool committed with docs and tests. @jfowkes please note we now have a ccf tool, and you will want to update your python wrapper accordingly

**Comment by jfowkes** [comment]
Ooh this is an exciting new addition, but atm I just call `ccfg` with `NULL` for the Jacobian which seem to work just fine.

**Comment by nimgould** [comment]
Good, as we said before, there are many ways around this, but this will be the most efficient (probably not a python concern, I'll admit!). No point in breaking things if they don't need to be.

**Comment by amontoison** [comment]
Thanks Nick!
It's now used in the Julia interface:
- https://github.com/JuliaSmoothOptimizers/CUTEst.jl/pull/398/files
- https://github.com/JuliaPackaging/Yggdrasil/pull/9323

It is now very easy to interface new features of CUTEst/GALAHAD in the Julia interfaces.
I have automated everything so that it will be simple to maintain in the future.

Just a note: the file `cutest_ccf.pdf` is missing in the directory `doc/pdf`.

**Comment by nimgould** [comment]
Thank you. I have commited the missing cutest_ccf* pdf files I forgot to git add
