### ISSUE TITLE
cutest2matlab: undefined reference to `FORTRAN_open_r'

### ISSUE THREAD

**Issue by zaikunzhang** [ralna/CUTEst#69]
Hi @amontoison Alexis, 

[MATCUTEst](https://github.com/matcutest/matcutest) cannot compile the latest version of CUTEst (Release 2.3.0) anymore, because [`cutest2matlab`](https://github.com/ralna/CUTEst/blob/master/bin/cutest2matlab) complains about  "undefined reference to `FORTRAN_open_r'".

The error occurs when running [getcup.m](https://github.com/matcutest/matcutest/blob/main/mtools/src/getcup.m), whose major work is to call [`cutest2matlab`](https://github.com/ralna/CUTEst/blob/master/bin/cutest2matlab) on each problem: 

https://github.com/matcutest/matcutest/blob/main/mtools/src/getcup.m#L94

The error is as follows:

```
/usr/bin/ld: cutest/objects/pc64.lnx.gfo/double/mcutest.o: in function `mexFunction':
cutest/objects/pc64.lnx.gfo/double/mcutest.c:289: undefined reference to `FORTRAN_open_r'
/usr/bin/ld: cutest/objects/pc64.lnx.gfo/double/mcutest.c:379: undefined reference to `FORTRAN_open_r'
/usr/bin/ld: cutest/objects/pc64.lnx.gfo/double/mcutest.c:485: undefined reference to `FORTRAN_close_r'
collect2: error: ld returned 1 exit status
```

See https://github.com/matcutest/matcutest/actions/runs/11287802919/job/31394364167 for a complete log file on GitHub Actions. 

If you would like to reproduce locally, you may try
```
git clone git@github.com:matcutest/matcutest.git && cd matcutest && bash ./INSTALL
```
It requires Ubuntu 22.04 or above, MATLAB R2022a or above, gcc-10 and gfortran-10. 

Thank you for taking a look. 

Best regards,
Zaikun

**Comment by nimgould** [comment]
@amontoison, @zaikunzhang  I think that this is a mistake I made a month ago when I changed the names of the fortran_open and fortran_closed procedures to be precision dependent. I shouldn't have done that on the C side. Zaikun, I have pushed a fix, could you please try again, and let me know

**Comment by zaikunzhang** [comment]
Hi Nick @nimgould ,

Thank you very much for the prompt response. It works!

Best regards,
Zaikun

**Comment by nimgould** [comment]
I'm pleased, and apologize for the errors

**Comment by amontoison** [comment]
@zaikunzhang Do you need a new release of CUTEst?
I can do a release `2.3.1` with the fixes of Nick.
Glad to see you back on GitHub :)

**Comment by zaikunzhang** [comment]
Thanks @nimgould and @amontoison !

> Do you need a new release of CUTEst?

Not needed. In fact, MatCUTEst always clones the main branch of CUTEst (of course, this is not the best way).

> Glad to see you back on GitHub :)

Thank you. I have been very busy, which may continue for another few weeks ...
